import Head from "next/head";
import { useEffect, useState } from "react";
import Banner3 from "../components/banner/Banner3";
import Home1Banner from "../components/banner/Home1Banner";
import Preloader from "../components/common/Preloader";
import ScrollProgrssBtn from "../components/common/ScrollProgrssBtn";
import Home1Destination from "../components/destination/Home1Destination";
import Footer1 from "../components/footer/Footer1";
import Header1 from "../components/header/Header1";
import Home1SearchBar from "../components/home/Home1SearchBar";
import Home1Offer from "../components/offer/Home1Offer";
import Home2Offer from "../components/offer/Home2Offer";

export default function Home() {
  const [loading, setloading] = useState(false);
  useEffect(() => {
    setloading(false);
    setTimeout(() => setloading(true), 3000);
  }, []);
  return (
    <>
      {!loading ? (
        <>
          <Head>
            <title>Loading</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/icons/logo-icon.svg" />
          </Head>
          <Preloader loader="home1preloader" />
        </>
      ) : (
        <>
          <Head>
            <title>Resa Tunisie</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/icons/logo-icon.svg" />
          </Head>
          <ScrollProgrssBtn />
          <Header1 />
          <Home1Banner />
          <Home1SearchBar />
          <Home1Offer />
          <Banner3 />
          <Home2Offer />
          <Home1Destination />
          <Footer1 />
        </>
      )}
    </>
  );
}
